# docker-compose.yml
version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: student_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - student_network

  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: 'postgresql://user:password@postgres:5432/student_db'
    ports:
      - "8000:8000"
    networks:
      - student_network

networks:
  student_network:
    driver: bridge

volumes:
  pg_data:
